apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    # This is the Docker network address for the Prometheus service
    url: http://prometheus:9090
    isDefault: true
    editable: false
